"use client";

import { useState } from "react";
import { Navigation } from "@/components/landing/navigation";
import { FooterSection } from "@/components/landing/footer-section";
import { ArrowLeft, Activity, Info, Sliders, CheckCircle2 } from "lucide-react";
import Link from "next/link";

const instrumentSpecs = {
  solexs: {
    title: "SoLEXS",
    fullName: "Solar Low Energy X-ray Spectrometer",
    range: "4 - 25 keV",
    resolution: "1s nominal, resampled to 1m",
    sensorType: "Silicon Drift Detector (SDD)",
    observations: "Soft X-ray flare precursors, hot plasma emissions, thermal heating phases.",
    desc: "A soft X-ray spectrometer designed to monitor solar irradiance. It provides high-cadence observations in the lower energy spectrum, mapping the early stages of plasma heating before a flare occurs.",
  },
  hel1os: {
    title: "HEL1OS",
    fullName: "High Energy L1 Orbiting Spectrometer",
    range: "10 - 150 keV",
    resolution: "1s nominal, resampled to 1m",
    sensorType: "CZT & NaI(Tl) Detectors",
    observations: "Hard X-ray flare emissions, non-thermal particle acceleration, impulsive phases.",
    desc: "Designed to capture the high-energy, impulsive stage of solar flares. It records non-thermal emissions generated by accelerated electrons slamming into the solar chromosphere.",
  },
  goes: {
    title: "NOAA GOES",
    fullName: "Geostationary Operational Environmental Satellite",
    range: "1 - 8 Å (soft) & 0.5 - 4 Å (hard)",
    resolution: "1s - 2s cadence",
    sensorType: "X-ray Sensor (XRS) Ionization Chambers",
    observations: "Global solar irradiance benchmarking, standard NOAA flare classifications.",
    desc: "The standard reference platform for space weather monitoring. It provides geostationary soft X-ray flux measurements used to benchmark and classify Aditya-L1 predictions.",
  },
};

export default function InstrumentsPage() {
  const [activeInst, setActiveInst] = useState<keyof typeof instrumentSpecs>("solexs");
  const [energySlider, setEnergySlider] = useState<number>(15); // keV

  // Determine active detector based on energy slider
  const getActiveDetectorByEnergy = (energy: number) => {
    if (energy < 4) return "goes";
    if (energy <= 10) return "solexs";
    if (energy < 25) return "solexs-hel1os"; // Overlap
    return "hel1os";
  };

  const activeDetector = getActiveDetectorByEnergy(energySlider);

  // Compute wave speed/frequency parameters based on energy slider
  const frequencyFactor = 0.05 + (energySlider / 150) * 0.45; // Higher energy = higher frequency
  const amplitude = 30 - (energySlider / 150) * 15; // Higher energy = slightly lower amplitude

  return (
    <main className="relative min-h-screen bg-black text-foreground overflow-x-hidden pt-24">
      <Navigation />

      <div className="max-w-[1400px] mx-auto px-6 lg:px-12 py-12">
        {/* Back Link */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-12 group"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          Back to Solar Observatory
        </Link>

        {/* Hero Header */}
        <div className="max-w-3xl mb-16">
          <span className="text-sm font-mono text-violet-500 uppercase tracking-wider block mb-4">Pipeline Step 03</span>
          <h1 className="text-5xl md:text-6xl font-display tracking-tight mb-6 leading-none">
            Spacecraft Payload & <br />
            <span className="text-muted-foreground">Instrumentation</span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground leading-relaxed">
            Our pipeline fuses telemetry from two primary payloads on India's Aditya-L1 spacecraft: 
            SoLEXS and HEL1OS. These space-borne spectrometers observe soft and hard X-rays respectively, 
            which we benchmark against NOAA's GOES reference satellites.
          </p>
        </div>

        {/* Main Content Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 mb-24">
          {/* Left Column: Wave & Energy Simulator (7 cols) */}
          <div className="lg:col-span-7 space-y-8">
            <div className="bg-card/50 backdrop-blur-md border border-border rounded-2xl p-6 lg:p-8 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-64 h-64 bg-violet-500/5 rounded-full blur-[80px] pointer-events-none" />
              <h3 className="font-semibold text-lg mb-6 flex items-center gap-2 text-foreground">
                <Activity className="w-5 h-5 text-violet-500" />
                Spectral Energy & Wave Simulator
              </h3>

              {/* Wave Animation Box */}
              <div className="relative w-full h-[200px] bg-black/40 rounded-xl border border-border/50 p-6 flex flex-col justify-between overflow-hidden">
                {/* Wave Canvas/SVG */}
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                  <svg className="w-full h-full" xmlns="http://www.w3.org/2000/svg">
                    <path
                      d={`M 0,100 ${Array.from({ length: 120 }, (_, i) => {
                        const x = i * 6;
                        const y = 100 + Math.sin(x * frequencyFactor) * amplitude;
                        return `L ${x},${y}`;
                      }).join(" ")}`}
                      stroke={
                        activeDetector === "goes"
                          ? "#10b981"
                          : activeDetector === "solexs"
                          ? "#8b5cf6"
                          : activeDetector === "solexs-hel1os"
                          ? "#f59e0b"
                          : "#ef4444"
                      }
                      strokeWidth="2"
                      fill="none"
                      className="transition-all duration-300"
                    />
                  </svg>
                </div>

                {/* Overlaid Info */}
                <div className="z-10 flex justify-between items-start">
                  <div>
                    <span className="text-[10px] font-mono text-muted-foreground block uppercase">Active Observability Range</span>
                    <span className="text-xl font-bold font-mono text-foreground">
                      {energySlider} keV
                    </span>
                  </div>

                  <div className="text-right">
                    <span className="text-[10px] font-mono text-muted-foreground block uppercase">Observing Sensor</span>
                    <span
                      className={`text-xs px-2.5 py-1 rounded-full border font-bold uppercase tracking-wider inline-block mt-1 ${
                        activeDetector === "goes"
                          ? "text-emerald-400 border-emerald-500/20 bg-emerald-500/10"
                          : activeDetector === "solexs"
                          ? "text-violet-400 border-violet-500/20 bg-violet-500/10"
                          : activeDetector === "solexs-hel1os"
                          ? "text-amber-400 border-amber-500/20 bg-amber-500/10"
                          : "text-rose-400 border-rose-500/20 bg-rose-500/10"
                      }`}
                    >
                      {activeDetector === "goes"
                        ? "NOAA GOES Only"
                        : activeDetector === "solexs"
                        ? "Aditya-L1 SoLEXS"
                        : activeDetector === "solexs-hel1os"
                        ? "SoLEXS + HEL1OS overlap"
                        : "Aditya-L1 HEL1OS"}
                    </span>
                  </div>
                </div>

                <div className="z-10 text-xs text-muted-foreground font-mono">
                  {energySlider < 10 ? "Soft X-Ray (Thermal plasma heating)" : "Hard X-Ray (Non-thermal particle acceleration)"}
                </div>
              </div>

              {/* Slider Control */}
              <div className="mt-8 space-y-4">
                <div className="flex justify-between text-xs font-mono">
                  <span className="text-muted-foreground">Select X-Ray Photon Energy</span>
                  <span className="text-foreground font-semibold">{energySlider} keV</span>
                </div>
                <input
                  type="range"
                  min="1"
                  max="150"
                  value={energySlider}
                  onChange={(e) => setEnergySlider(Number(e.target.value))}
                  className="w-full h-1.5 bg-black/40 rounded-lg appearance-none cursor-pointer accent-violet-500"
                />
                <div className="flex justify-between text-[10px] text-muted-foreground font-mono pt-1">
                  <span>1 keV (GOES soft band)</span>
                  <span>75 keV</span>
                  <span>150 keV (HEL1OS max band)</span>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column: Instrument Spec Selector (5 cols) */}
          <div className="lg:col-span-5 space-y-8">
            <div className="bg-card/50 backdrop-blur-md border border-border rounded-2xl p-6 lg:p-8 relative overflow-hidden flex flex-col h-full justify-between">
              <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/5 rounded-full blur-[80px] pointer-events-none" />
              <div>
                <h3 className="font-semibold text-lg mb-4 flex items-center gap-2 text-foreground">
                  <Info className="w-5 h-5 text-emerald-500" />
                  Instrument Specifications
                </h3>
                <p className="text-xs text-muted-foreground mb-6">
                  Select a solar payload instrument below to inspect its operational characteristics, spectral ranges, and sensor technology.
                </p>

                {/* Tabs */}
                <div className="flex gap-2 mb-6">
                  {(Object.keys(instrumentSpecs) as Array<keyof typeof instrumentSpecs>).map((key) => (
                    <button
                      key={key}
                      onClick={() => setActiveInst(key)}
                      className={`flex-1 py-2 px-3 rounded-lg border text-xs font-semibold transition-all text-center uppercase tracking-wider ${
                        activeInst === key
                          ? "border-emerald-500 bg-emerald-500/10 text-emerald-400"
                          : "border-border bg-black/20 text-muted-foreground hover:border-foreground/10 hover:text-foreground"
                      }`}
                    >
                      {instrumentSpecs[key].title}
                    </button>
                  ))}
                </div>

                {/* Spec details card */}
                <div className="bg-black/45 border border-border/40 rounded-xl p-5 space-y-4">
                  <div>
                    <span className="text-[9px] text-emerald-400 font-bold block uppercase tracking-wider">
                      {instrumentSpecs[activeInst].fullName}
                    </span>
                    <p className="text-xs text-muted-foreground leading-relaxed mt-2">
                      {instrumentSpecs[activeInst].desc}
                    </p>
                  </div>

                  <div className="grid grid-cols-2 gap-4 border-t border-border/30 pt-4 text-xs">
                    <div>
                      <span className="text-[10px] text-muted-foreground block">ENERGY/SPECTRAL RANGE</span>
                      <span className="font-semibold text-foreground font-mono">{instrumentSpecs[activeInst].range}</span>
                    </div>
                    <div>
                      <span className="text-[10px] text-muted-foreground block">TEMPORAL CADENCE</span>
                      <span className="font-semibold text-foreground">{instrumentSpecs[activeInst].resolution}</span>
                    </div>
                    <div className="col-span-2 pt-2">
                      <span className="text-[10px] text-muted-foreground block">DETECTOR SENSOR TYPE</span>
                      <span className="font-semibold text-foreground">{instrumentSpecs[activeInst].sensorType}</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-8 pt-4 border-t border-border/30 flex items-center gap-3 text-[11px] text-muted-foreground">
                <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" />
                Data sourced directly from ISRO and NOAA instrumentation manuals.
              </div>
            </div>
          </div>
        </div>

        {/* Payload Specifications Table */}
        <div className="bg-card/50 backdrop-blur-md border border-border rounded-2xl p-6 lg:p-8 relative overflow-hidden">
          <h3 className="font-semibold text-lg mb-6 flex items-center gap-2 text-foreground">
            <Sliders className="w-5 h-5 text-violet-500" />
            Operational Payloads Matrix
          </h3>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-border text-muted-foreground font-mono">
                  <th className="py-3 px-4 uppercase font-medium">Instrument</th>
                  <th className="py-3 px-4 uppercase font-medium">Spacecraft</th>
                  <th className="py-3 px-4 uppercase font-medium">Primary Range</th>
                  <th className="py-3 px-4 uppercase font-medium">Sensor Technology</th>
                  <th className="py-3 px-4 uppercase font-medium">Science Objective</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/40 text-muted-foreground">
                <tr className="hover:bg-white/5 transition-colors">
                  <td className="py-4 px-4 font-semibold text-foreground">SoLEXS</td>
                  <td className="py-4 px-4">Aditya-L1 (ISRO)</td>
                  <td className="py-4 px-4 font-mono text-violet-400">4 - 25 keV</td>
                  <td className="py-4 px-4">Silicon Drift Detector</td>
                  <td className="py-4 px-4">Soft X-ray thermal plasma heating & pre-flare thermal emissions.</td>
                </tr>
                <tr className="hover:bg-white/5 transition-colors">
                  <td className="py-4 px-4 font-semibold text-foreground">HEL1OS</td>
                  <td className="py-4 px-4">Aditya-L1 (ISRO)</td>
                  <td className="py-4 px-4 font-mono text-rose-400">10 - 150 keV</td>
                  <td className="py-4 px-4">CZT and NaI(Tl) Detectors</td>
                  <td className="py-4 px-4">Hard X-ray non-thermal electron acceleration during impulsive phase.</td>
                </tr>
                <tr className="hover:bg-white/5 transition-colors">
                  <td className="py-4 px-4 font-semibold text-foreground">GOES XRS</td>
                  <td className="py-4 px-4">GOES-R (NOAA)</td>
                  <td className="py-4 px-4 font-mono text-emerald-400">1-8 Å & 0.5-4 Å</td>
                  <td className="py-4 px-4">Ionization Chambers</td>
                  <td className="py-4 px-4">Standard soft X-ray flux classification and baseline validation.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <FooterSection />
    </main>
  );
}
