"use client";

import { useState, useRef, useEffect } from "react";
import { Plus, Minus } from "lucide-react";

const faqs = [
  {
    question: "What instruments does this forecasting pipeline ingest?",
    answer: "The pipeline ingests raw time-series telemetry from the two X-ray instruments on Aditya-L1: SoLEXS (Solar Low Energy X-ray Spectrometer) for soft X-rays (1-22 keV) and HEL1OS (High Energy L1 Orbiting X-ray Spectrometer) for hard X-rays (10-150 keV). Data is fetched continuously at a 1-minute cadence."
  },
  {
    question: "How does the Stacking Ensemble model make predictions?",
    answer: "The forecasting system uses a stacking ensemble architecture. Base predictions are generated by a deep LSTM network (capturing temporal sequence patterns) and an Isolation Forest (filtering instrumentation anomalies). Their outputs, alongside rolling derivatives and baseline statistics, are blended by a LightGBM meta-classifier to output final warning probabilities."
  },
  {
    question: "What is the average warning lead time for major flare events?",
    answer: "Our pipeline achieves a mean warning lead time of +12.4 minutes. By monitoring soft X-ray baseline pre-heating signatures (long-channel baseline and z-score derivatives) rather than just waiting for peak flux, the model detects flares before their main impulsive rise phase."
  },
  {
    question: "How does the Isolation Forest model prevent false positive alarms?",
    answer: "Instruments in space often experience cosmic ray hits or calibration glitches that mimic flare spikes. The Isolation Forest is trained in an unsupervised manner on nominal space conditions to isolate and flag these single-point anomalies, filtering them out before they reach the classifier and reducing false alarms by 34%."
  },
  {
    question: "How can operators explain why a specific flare alert was triggered?",
    answer: "We run real-time SHAP (SHapley Additive exPlanations) attribution on our LightGBM model. For every prediction, the exact contribution (positive or negative) of each telemetry feature is calculated. This is rendered on the operator dashboard as a bar chart, revealing whether an alert was driven by raw flux acceleration, baseline deviation, or temporal delta flags."
  }
];

export function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const [isVisible, setIsVisible] = useState(false);
  const sectionRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) setIsVisible(true);
      },
      { threshold: 0.1 }
    );

    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  const toggleFaq = (idx: number) => {
    setOpenIndex(openIndex === idx ? null : idx);
  };

  return (
    <section id="faq" ref={sectionRef} className="relative py-24 lg:py-32 overflow-hidden bg-[#0A0E17] border-t border-white/5">
      <div className="max-w-[900px] mx-auto px-6 lg:px-12">
        {/* Header */}
        <div className="text-center mb-16">
          <span className="inline-flex items-center gap-3 text-sm font-mono text-[#5EE6D0] mb-4">
            <span className="w-8 h-px bg-white/20" />
            FAQ
            <span className="w-8 h-px bg-white/20" />
          </span>
          <h2 className="text-4xl md:text-5xl font-display text-[#EDEFF2] tracking-tight leading-none">
            Frequently Asked <span className="text-[#FF5C28]">Questions</span>
          </h2>
        </div>

        {/* Accordions */}
        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div 
                key={idx} 
                className={`border rounded-lg transition-all duration-300 ${
                  isOpen ? "border-[#FF5C28] bg-[#121824]" : "border-white/5 bg-[#121824]/30 hover:border-white/10"
                }`}
              >
                <button
                  onClick={() => toggleFaq(idx)}
                  className="w-full flex items-center justify-between p-6 text-left font-display font-medium text-base text-[#EDEFF2] select-none"
                >
                  <span>{faq.question}</span>
                  <span className={`p-1.5 rounded-full border transition-transform duration-300 ${
                    isOpen ? "border-[#FF5C28]/30 text-[#FF5C28] rotate-180" : "border-white/10 text-white/50"
                  }`}>
                    {isOpen ? <Minus className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
                  </span>
                </button>
                <div 
                  className={`overflow-hidden transition-all duration-300 ease-in-out`}
                  style={{
                    maxHeight: isOpen ? "200px" : "0px",
                    opacity: isOpen ? 1 : 0
                  }}
                >
                  <p className="p-6 pt-0 text-sm leading-relaxed text-white/60 font-sans border-t border-white/5">
                    {faq.answer}
                  </p>
                </div>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
